In [1]:
import numpy as np

In [2]:
ob=np.array([22,17,20,26,22,13])
es=np.array([20,20,20,20,20,20])

In [3]:
ob-es

array([ 2, -3,  0,  6,  2, -7])

In [4]:
np.sum(np.square(ob-es)/es)

5.1000000000000005

In [5]:
import scipy.stats as st

In [6]:
chi_table=st.chi.ppf(0.05,3)
chi_table

0.5931663491376357

In [7]:
row1=np.array([40,45,25,10])
row2=np.array([35,30,20,30])

In [8]:
sum_r1=np.sum(row1)
sum_r2=np.sum(row2)

In [9]:
import pandas as pd

In [10]:
dataset=pd.DataFrame([row1,row2])

In [11]:
dataset

0   1   2   3
0  40  45  25  10
1  35  30  20  30

In [12]:
sum_c1=np.sum(dataset[0])
sum_c2=np.sum(dataset[1])
sum_c3=np.sum(dataset[2])
sum_c4=np.sum(dataset[3])

In [13]:
sum_cal=np.array([sum_c1,sum_c2,sum_c3,sum_c4])

In [14]:
sum_cal

array([75, 75, 45, 40], dtype=int64)

In [15]:
sum_cal=row1+row2

In [16]:
sum_cal

array([75, 75, 45, 40])

In [17]:
sum_row=np.array([sum_r1,sum_r2])

In [18]:
sum_row

array([120, 115])

In [19]:
n=235
exp = []
for i in range(0,2):
    for j in range(0,4):
        value=(sum_row[i]*sum_cal[j])/n
        exp.append(value)
        

In [20]:
exp

[38.297872340425535,
 38.297872340425535,
 22.97872340425532,
 20.425531914893618,
 36.702127659574465,
 36.702127659574465,
 22.02127659574468,
 19.574468085106382]

In [21]:
obj=np.array([40,45,25,10,35,30,20,30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [22]:
chi_cal=np.sum(np.square(obj-exp)/exp)

In [23]:
chi_cal

13.788747987117553